### ISSUE TITLE
An agnostic way to fetch apps from http based sources?

### ISSUE THREAD

**Issue by pony-montana** [zapstore/releastr#11]
HI, I would suggest to add electrum android wallet to the app store, but trying to understand how to do that I encounter some limitations.
The app is updated on the official electrum website https://electrum.org/#download ; how we should fetch the http link to the app? 
with https://github.com/ImranR98/Obtainium you can utilize a regex-based scanning system to make "every webpage a repo".
How it should be made here? :)

**Comment by pony-montana** [comment]
oh, I just see #1 😅

**Comment by franzaps** [comment]
Haha exactly, will fix soon!
